/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogue
         * @description Public on purpose: reference prices are the transparency the platform exists to provide.
         */
        get: operations["catalogue_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lots */
        get: operations["list_lots_lots_get"];
        put?: never;
        /** Create Lot */
        post: operations["create_lot_lots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lot */
        get: operations["get_lot_lots__lot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lot Photo */
        get: operations["lot_photo_lots__lot_id__photo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Lot */
        post: operations["confirm_lot_lots__lot_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List Lot */
        post: operations["list_lot_lots__lot_id__list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bids
         * @description Sealed until close: before then a buyer sees only their own bid and the seller none.
         */
        get: operations["bids_lots__lot_id__bids_get"];
        put?: never;
        /** Place Bid */
        post: operations["place_bid_lots__lot_id__bids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/escrow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Escrow */
        post: operations["start_escrow_lots__lot_id__escrow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/pickup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Pickup */
        post: operations["schedule_pickup_lots__lot_id__pickup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Delivery */
        post: operations["record_delivery_lots__lot_id__delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/weighbridge-slip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weighbridge Slip */
        get: operations["weighbridge_slip_lots__lot_id__weighbridge_slip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/delivery/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Delivery */
        post: operations["accept_delivery_lots__lot_id__delivery_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/delivery/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispute Delivery */
        post: operations["dispute_delivery_lots__lot_id__delivery_dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/custody": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Custody Record
         * @description Parties to the trade only: the record carries the seller's reserve and the award.
         */
        get: operations["custody_record_lots__lot_id__custody_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{intent_id}/simulate-capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Capture
         * @description Stands in for the buyer completing checkout. Only works for simulated-gateway intents.
         */
        post: operations["simulate_capture_payments__intent_id__simulate_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/razorpay/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Razorpay Verify
         * @description Checkout's success callback. Lets escrow fund without a public webhook URL (sandbox);
         *     the webhook stays as the reconciliation path, and capture is idempotent across both.
         */
        post: operations["razorpay_verify_payments_razorpay_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/razorpay/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Razorpay Webhook */
        post: operations["razorpay_webhook_payments_razorpay_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificate */
        get: operations["certificate_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificate Pdf */
        get: operations["certificate_pdf_certificates__certificate_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify
         * @description Public: anyone holding the certificate (an auditor, a regulator) can check it.
         */
        get: operations["verify_certificates__certificate_id__verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wallet */
        get: operations["wallet_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Kyc */
        post: operations["decide_kyc_admin_users__user_id__kyc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/materials/{code}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Rate */
        put: operations["set_rate_admin_materials__code__rate_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AwardOut */
        AwardOut: {
            buyer: components["schemas"]["PartyOut"];
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /** Escrow Required Paise */
            escrow_required_paise: number;
        };
        /** BidIn */
        BidIn: {
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
        };
        /** BidOut */
        BidOut: {
            buyer: components["schemas"]["PartyOut"];
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
        };
        /** Body_create_lot_lots_post */
        Body_create_lot_lots_post: {
            /**
             * Photo
             * @description Photograph of the lot
             */
            photo: string;
        };
        /** Body_record_delivery_lots__lot_id__delivery_post */
        Body_record_delivery_lots__lot_id__delivery_post: {
            /** Measured Weight Grams */
            measured_weight_grams: number;
            /**
             * Slip
             * @description Photograph of the weighbridge slip
             */
            slip: string;
        };
        /** CatalogueOut */
        CatalogueOut: {
            /** Materials */
            materials: components["schemas"]["MaterialOut"][];
            /** Grades */
            grades: components["schemas"]["GradeOut"][];
        };
        /** CertificateOut */
        CertificateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /** Head Hash */
            head_hash: string;
            /** Event Count */
            event_count: number;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Verify Url */
            verify_url: string;
        };
        /** CheckoutResultIn */
        CheckoutResultIn: {
            /** Razorpay Order Id */
            razorpay_order_id: string;
            /** Razorpay Payment Id */
            razorpay_payment_id: string;
            /** Razorpay Signature */
            razorpay_signature: string;
        };
        /** ClassificationOut */
        ClassificationOut: {
            /** Suggested Material Code */
            suggested_material_code: string | null;
            /** Suggested Grade */
            suggested_grade: string | null;
            /** Confidence */
            confidence: number | null;
            /** Prefilled */
            prefilled: boolean;
            /** Threshold */
            threshold: number;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /** Material Code */
            material_code: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "A" | "B" | "C";
            /** Declared Weight Grams */
            declared_weight_grams: number;
        };
        /** CustodyEventOut */
        CustodyEventOut: {
            /** Seq */
            seq: number;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Actor Id */
            actor_id: string | null;
            /** Recorded At */
            recorded_at: string;
            /** Prev Hash */
            prev_hash: string;
            /** Hash */
            hash: string;
        };
        /** DisputeIn */
        DisputeIn: {
            /** Reason */
            reason: string;
        };
        /** EscrowOut */
        EscrowOut: {
            /**
             * Intent Id
             * Format: uuid
             */
            intent_id: string;
            /** Gateway */
            gateway: string;
            /** Gateway Order Id */
            gateway_order_id: string;
            /** Amount Paise */
            amount_paise: number;
            /** Status */
            status: string;
            /** Razorpay Key Id */
            razorpay_key_id?: string | null;
        };
        /** EstimateOut */
        EstimateOut: {
            /** Reference Rate Paise Per Kg */
            reference_rate_paise_per_kg: number;
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /** Total Paise */
            total_paise: number;
            /** Low Paise */
            low_paise: number;
            /** High Paise */
            high_paise: number;
        };
        /** GradeOut */
        GradeOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Multiplier */
            multiplier: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KycDecisionIn */
        KycDecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Note */
            note?: string | null;
        };
        /**
         * KycStatus
         * @enum {string}
         */
        KycStatus: "pending" | "approved" | "rejected";
        /** ListIn */
        ListIn: {
            /**
             * Auction Hours
             * @default 24
             */
            auction_hours: number;
            /** Reserve Rate Paise Per Kg */
            reserve_rate_paise_per_kg?: number | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Phone */
            phone: string;
            /** Password */
            password: string;
        };
        /** LotOut */
        LotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            seller: components["schemas"]["PartyOut"];
            /** Photo Url */
            photo_url: string;
            /** Photo Sha256 */
            photo_sha256: string;
            classification: components["schemas"]["ClassificationOut"];
            /** Material Code */
            material_code: string | null;
            /** Material Name */
            material_name: string | null;
            /** Grade */
            grade: string | null;
            /** Declared Weight Grams */
            declared_weight_grams: number | null;
            estimate: components["schemas"]["EstimateOut"] | null;
            /** Reserve Rate Paise Per Kg */
            reserve_rate_paise_per_kg: number | null;
            /** Auction Closes At */
            auction_closes_at: string | null;
            /** Bid Count */
            bid_count: number;
            /** My Bid Rate Paise Per Kg */
            my_bid_rate_paise_per_kg: number | null;
            award: components["schemas"]["AwardOut"] | null;
            /** Pickup At */
            pickup_at: string | null;
            /** Measured Weight Grams */
            measured_weight_grams: number | null;
            /** Settled Amount Paise */
            settled_amount_paise: number | null;
            /** Certificate Id */
            certificate_id: string | null;
        };
        /** MaterialOut */
        MaterialOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Family */
            family: string;
            /** Description */
            description: string;
            /** Reference Rate Paise Per Kg */
            reference_rate_paise_per_kg: number | null;
            /** Rate Effective From */
            rate_effective_from: string | null;
        };
        /** PartyOut */
        PartyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Business Name */
            business_name: string | null;
        };
        /** PickupIn */
        PickupIn: {
            /**
             * Pickup At
             * Format: date-time
             */
            pickup_at: string;
        };
        /** RateIn */
        RateIn: {
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Phone */
            phone: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "seller" | "buyer";
            /** Business Name */
            business_name?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** Pan */
            pan?: string | null;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Business Name */
            business_name: string | null;
            /** Gstin */
            gstin: string | null;
            /** Pan */
            pan: string | null;
            /** Kyc Status */
            kyc_status: string;
            /** Kyc Note */
            kyc_note: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationOut */
        VerificationOut: {
            /**
             * Certificate Id
             * Format: uuid
             */
            certificate_id: string;
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /** Valid */
            valid: boolean;
            /** Reason */
            reason: string | null;
            /** Head Hash */
            head_hash: string;
            /** Event Count */
            event_count: number;
            /** Pdf Sha256 */
            pdf_sha256: string;
        };
        /** WalletEntryOut */
        WalletEntryOut: {
            /** Kind */
            kind: string;
            /** Lot Id */
            lot_id: string | null;
            /** Amount Paise */
            amount_paise: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WalletOut */
        WalletOut: {
            /** Balance Paise */
            balance_paise: number;
            /** Entries */
            entries: components["schemas"]["WalletEntryOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    catalogue_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueOut"];
                };
            };
        };
    };
    list_lots_lots_get: {
        parameters: {
            query?: {
                scope?: "mine" | "market";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lot_lots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_lot_lots_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lot_lots__lot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lot_photo_lots__lot_id__photo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_lot_lots__lot_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lot_lots__lot_id__list_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bids_lots__lot_id__bids_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_bid_lots__lot_id__bids_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_escrow_lots__lot_id__escrow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_pickup_lots__lot_id__pickup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_delivery_lots__lot_id__delivery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_record_delivery_lots__lot_id__delivery_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weighbridge_slip_lots__lot_id__weighbridge_slip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_delivery_lots__lot_id__delivery_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_delivery_lots__lot_id__delivery_dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    custody_record_lots__lot_id__custody_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustodyEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_capture_payments__intent_id__simulate_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    razorpay_verify_payments_razorpay_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutResultIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    razorpay_webhook_payments_razorpay_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    certificate_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    certificate_pdf_certificates__certificate_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificates__certificate_id__verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wallet_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletOut"];
                };
            };
        };
    };
    users_admin_users_get: {
        parameters: {
            query?: {
                kyc_status?: components["schemas"]["KycStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_kyc_admin_users__user_id__kyc_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KycDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_rate_admin_materials__code__rate_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
