/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogue
         * @description Public on purpose: reference prices are the transparency the platform exists to provide.
         */
        get: operations["catalogue_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{code}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rate History
         * @description Newest first. Public, like the catalogue: how a price got here is part of its case.
         */
        get: operations["rate_history_materials__code__rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lots */
        get: operations["list_lots_lots_get"];
        put?: never;
        /** Create Lot */
        post: operations["create_lot_lots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lot */
        get: operations["get_lot_lots__lot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lot Photo */
        get: operations["lot_photo_lots__lot_id__photo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Lot */
        post: operations["confirm_lot_lots__lot_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List Lot */
        post: operations["list_lot_lots__lot_id__list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bids
         * @description Sealed until close: before then a buyer sees only their own bid and the seller none.
         */
        get: operations["bids_lots__lot_id__bids_get"];
        put?: never;
        /** Place Bid */
        post: operations["place_bid_lots__lot_id__bids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline Award
         * @description The winning buyer can't go ahead; the lot passes to the next bid straight away.
         */
        post: operations["decline_award_lots__lot_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/escrow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Escrow */
        post: operations["start_escrow_lots__lot_id__escrow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/pickup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Pickup */
        post: operations["schedule_pickup_lots__lot_id__pickup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Delivery */
        post: operations["record_delivery_lots__lot_id__delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/weighbridge-slip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weighbridge Slip */
        get: operations["weighbridge_slip_lots__lot_id__weighbridge_slip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/delivery/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Delivery */
        post: operations["accept_delivery_lots__lot_id__delivery_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/delivery/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispute Delivery */
        post: operations["dispute_delivery_lots__lot_id__delivery_dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/dispute/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Dispute
         * @description Admin only: settle at an agreed weight, or cancel and refund the buyer.
         */
        post: operations["resolve_dispute_lots__lot_id__dispute_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/custody": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Custody Record
         * @description Parties to the trade only: the record carries the seller's reserve and the award.
         */
        get: operations["custody_record_lots__lot_id__custody_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lots/{lot_id}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice
         * @description Draft tax invoice for a settled trade, for its parties.
         */
        get: operations["invoice_lots__lot_id__invoice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{intent_id}/simulate-capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Capture
         * @description Stands in for the buyer completing checkout. Only works for simulated-gateway intents.
         */
        post: operations["simulate_capture_payments__intent_id__simulate_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/razorpay/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Razorpay Verify
         * @description Checkout's success callback. Lets escrow fund without a public webhook URL (sandbox);
         *     the webhook stays as the reconciliation path, and capture is idempotent across both.
         */
        post: operations["razorpay_verify_payments_razorpay_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/razorpay/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Razorpay Webhook */
        post: operations["razorpay_webhook_payments_razorpay_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificate */
        get: operations["certificate_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificate Pdf */
        get: operations["certificate_pdf_certificates__certificate_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify
         * @description Public: anyone holding the certificate (an auditor, a regulator) can check it.
         */
        get: operations["verify_certificates__certificate_id__verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wallet */
        get: operations["wallet_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rfqs */
        get: operations["list_rfqs_rfqs_get"];
        put?: never;
        /** Post Rfq */
        post: operations["post_rfq_rfqs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rfqs/{rfq_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Rfq */
        post: operations["close_rfq_rfqs__rfq_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Partners
         * @description Sellers the signed-in buyer has bought from: who they can propose an agreement to.
         */
        get: operations["partners_agreements_partners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agreements */
        get: operations["list_agreements_agreements_get"];
        put?: never;
        /** Propose */
        post: operations["propose_agreements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{agreement_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_agreements__agreement_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{agreement_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline */
        post: operations["decline_agreements__agreement_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Impact
         * @description Weight recycled and emissions avoided through settled trades (illustrative factors).
         */
        get: operations["impact_impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Kyc */
        post: operations["decide_kyc_admin_users__user_id__kyc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/materials/{code}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Rate */
        put: operations["set_rate_admin_materials__code__rate_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disputes
         * @description Every trade on hold, oldest first: the money waits in escrow until an admin resolves it.
         */
        get: operations["disputes_admin_disputes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/transporters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transporters */
        get: operations["transporters_admin_transporters_get"];
        put?: never;
        /** Add Transporter */
        post: operations["add_transporter_admin_transporters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route
         * @description The day's booked pickups in a suggested visiting order (Indian calendar day).
         */
        get: operations["route_admin_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anchors */
        get: operations["anchors_admin_anchors_get"];
        put?: never;
        /** Seal */
        post: operations["seal_admin_anchors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/anchors/{anchor_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check */
        get: operations["check_admin_anchors__anchor_id__check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Now */
        post: operations["run_now_admin_jobs__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgreementIn */
        AgreementIn: {
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /** Material Code */
            material_code: string;
            /** Monthly Quantity Grams */
            monthly_quantity_grams: number;
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /** Months */
            months: number;
        };
        /** AgreementOut */
        AgreementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            buyer: components["schemas"]["PartyOut"];
            seller: components["schemas"]["PartyOut"];
            /** Material Code */
            material_code: string;
            /** Material Name */
            material_name: string;
            /** Monthly Quantity Grams */
            monthly_quantity_grams: number;
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /** Months */
            months: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
        };
        /** AnchorCheckOut */
        AnchorCheckOut: {
            /** Id */
            id: number;
            /** Holds */
            holds: boolean;
        };
        /** AnchorOut */
        AnchorOut: {
            /** Id */
            id: number;
            /** First Event Id */
            first_event_id: number;
            /** Last Event Id */
            last_event_id: number;
            /** Event Count */
            event_count: number;
            /** Merkle Root */
            merkle_root: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AwardOut */
        AwardOut: {
            buyer: components["schemas"]["PartyOut"];
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /** Escrow Required Paise */
            escrow_required_paise: number;
            /** Escrow Due At */
            escrow_due_at: string | null;
        };
        /** BidIn */
        BidIn: {
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
        };
        /** BidOut */
        BidOut: {
            buyer: components["schemas"]["PartyOut"];
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
            /** Lapsed */
            lapsed: boolean;
        };
        /** Body_create_lot_lots_post */
        Body_create_lot_lots_post: {
            /**
             * Photo
             * @description Photograph of the lot
             */
            photo: string;
        };
        /** Body_record_delivery_lots__lot_id__delivery_post */
        Body_record_delivery_lots__lot_id__delivery_post: {
            /** Measured Weight Grams */
            measured_weight_grams: number;
            /**
             * Slip
             * @description Photograph of the weighbridge slip
             */
            slip: string;
        };
        /** CatalogueOut */
        CatalogueOut: {
            /** Materials */
            materials: components["schemas"]["MaterialOut"][];
            /** Grades */
            grades: components["schemas"]["GradeOut"][];
            pricing_rule: components["schemas"]["PricingRuleOut"];
        };
        /** CertificateOut */
        CertificateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /** Head Hash */
            head_hash: string;
            /** Event Count */
            event_count: number;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Verify Url */
            verify_url: string;
        };
        /** CheckoutResultIn */
        CheckoutResultIn: {
            /** Razorpay Order Id */
            razorpay_order_id: string;
            /** Razorpay Payment Id */
            razorpay_payment_id: string;
            /** Razorpay Signature */
            razorpay_signature: string;
        };
        /** ClassificationOut */
        ClassificationOut: {
            /** Suggested Material Code */
            suggested_material_code: string | null;
            /** Suggested Grade */
            suggested_grade: string | null;
            /** Confidence */
            confidence: number | null;
            /** Prefilled */
            prefilled: boolean;
            /** Threshold */
            threshold: number;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /** Material Code */
            material_code: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "A" | "B" | "C";
            /** Declared Weight Grams */
            declared_weight_grams: number;
        };
        /** CustodyEventOut */
        CustodyEventOut: {
            /** Seq */
            seq: number;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Actor Id */
            actor_id: string | null;
            /** Recorded At */
            recorded_at: string;
            /** Prev Hash */
            prev_hash: string;
            /** Hash */
            hash: string;
        };
        /** DisputeIn */
        DisputeIn: {
            /** Reason */
            reason: string;
        };
        /** DisputeInfoOut */
        DisputeInfoOut: {
            /**
             * Raised By
             * @enum {string}
             */
            raised_by: "seller" | "escrow";
            /** Reason */
            reason: string;
            /** Raised At */
            raised_at: string;
        };
        /** DisputeOut */
        DisputeOut: {
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /** Material Name */
            material_name: string;
            seller: components["schemas"]["PartyOut"];
            buyer: components["schemas"]["PartyOut"];
            dispute: components["schemas"]["DisputeInfoOut"];
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /** Declared Weight Grams */
            declared_weight_grams: number;
            /** Measured Weight Grams */
            measured_weight_grams: number;
            /** Escrow Held Paise */
            escrow_held_paise: number;
            /** Max Settle Weight Grams */
            max_settle_weight_grams: number;
        };
        /** EscrowOut */
        EscrowOut: {
            /**
             * Intent Id
             * Format: uuid
             */
            intent_id: string;
            /** Gateway */
            gateway: string;
            /** Gateway Order Id */
            gateway_order_id: string;
            /** Amount Paise */
            amount_paise: number;
            /** Status */
            status: string;
            /** Razorpay Key Id */
            razorpay_key_id?: string | null;
        };
        /** EstimateOut */
        EstimateOut: {
            /** Reference Rate Paise Per Kg */
            reference_rate_paise_per_kg: number;
            reference_rate: components["schemas"]["RateOut"] | null;
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /** Total Paise */
            total_paise: number;
            /** Low Paise */
            low_paise: number;
            /** High Paise */
            high_paise: number;
        };
        /** GradeOut */
        GradeOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Multiplier */
            multiplier: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImpactOut */
        ImpactOut: {
            /** Trades */
            trades: number;
            /** Weight Grams */
            weight_grams: number;
            /** Co2E Avoided Grams */
            co2e_avoided_grams: number;
            /** Materials */
            materials: components["schemas"]["MaterialImpactOut"][];
        };
        /** InvoiceOut */
        InvoiceOut: {
            /** Number */
            number: string;
            /**
             * Draft
             * @default true
             */
            draft: boolean;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            supplier: components["schemas"]["InvoicePartyOut"];
            recipient: components["schemas"]["InvoicePartyOut"];
            /** Description */
            description: string;
            /** Hsn */
            hsn: string | null;
            /** Quantity Grams */
            quantity_grams: number;
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /** Taxable Paise */
            taxable_paise: number;
            /** Taxes */
            taxes: components["schemas"]["TaxLineOut"][];
            /** Total Paise */
            total_paise: number;
            /** Reverse Charge */
            reverse_charge: boolean;
        };
        /** InvoicePartyOut */
        InvoicePartyOut: {
            /** Name */
            name: string;
            /** Gstin */
            gstin: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Name */
            name: string;
            /** Schedule */
            schedule: string;
            /** Description */
            description: string;
            last_run: components["schemas"]["JobRunOut"] | null;
        };
        /** JobRunOut */
        JobRunOut: {
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Ok */
            ok: boolean;
            /** Summary */
            summary: string;
        };
        /** KycDecisionIn */
        KycDecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Note */
            note?: string | null;
            /**
             * Authorisations
             * @default []
             */
            authorisations: ("e_waste" | "battery")[];
        };
        /**
         * KycStatus
         * @enum {string}
         */
        KycStatus: "pending" | "approved" | "rejected";
        /** ListIn */
        ListIn: {
            /**
             * Auction Hours
             * @default 24
             */
            auction_hours: number;
            /** Reserve Rate Paise Per Kg */
            reserve_rate_paise_per_kg?: number | null;
        };
        /** LocationOut */
        LocationOut: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Phone */
            phone: string;
            /** Password */
            password: string;
        };
        /** LotOut */
        LotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            seller: components["schemas"]["PartyOut"];
            /** Photo Url */
            photo_url: string;
            /** Photo Sha256 */
            photo_sha256: string;
            classification: components["schemas"]["ClassificationOut"];
            /** Material Code */
            material_code: string | null;
            /** Material Name */
            material_name: string | null;
            /** Material Authorisation */
            material_authorisation: string | null;
            /** Grade */
            grade: string | null;
            /** Declared Weight Grams */
            declared_weight_grams: number | null;
            estimate: components["schemas"]["EstimateOut"] | null;
            /** Reserve Rate Paise Per Kg */
            reserve_rate_paise_per_kg: number | null;
            /** Auction Closes At */
            auction_closes_at: string | null;
            /** Bid Count */
            bid_count: number;
            /** My Bid Rate Paise Per Kg */
            my_bid_rate_paise_per_kg: number | null;
            /** My Bid Lapsed */
            my_bid_lapsed: boolean;
            award: components["schemas"]["AwardOut"] | null;
            /** Pickup At */
            pickup_at: string | null;
            pickup_location: components["schemas"]["LocationOut"] | null;
            /** Measured Weight Grams */
            measured_weight_grams: number | null;
            /** Settled Weight Grams */
            settled_weight_grams: number | null;
            /** Settled Amount Paise */
            settled_amount_paise: number | null;
            /** Certificate Id */
            certificate_id: string | null;
            dispute: components["schemas"]["DisputeInfoOut"] | null;
        };
        /** MaterialImpactOut */
        MaterialImpactOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Trades */
            trades: number;
            /** Weight Grams */
            weight_grams: number;
            /** Co2E Avoided Grams */
            co2e_avoided_grams: number;
        };
        /** MaterialOut */
        MaterialOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Family */
            family: string;
            /** Description */
            description: string;
            /** Authorisation */
            authorisation: string | null;
            /** Reference Rate Paise Per Kg */
            reference_rate_paise_per_kg: number | null;
            /** Rate Effective From */
            rate_effective_from: string | null;
            rate: components["schemas"]["RateOut"] | null;
        };
        /** PartyOut */
        PartyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Business Name */
            business_name: string | null;
        };
        /** PickupIn */
        PickupIn: {
            /**
             * Pickup At
             * Format: date-time
             */
            pickup_at: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /**
         * PricingRuleOut
         * @description How the reprice job moves prices, for explaining it on screen.
         */
        PricingRuleOut: {
            /** Window Days */
            window_days: number;
            /** Min Trades */
            min_trades: number;
            /** Blend Percent */
            blend_percent: number;
            /** Max Step Percent */
            max_step_percent: number;
        };
        /** RateIn */
        RateIn: {
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
        };
        /**
         * RateOut
         * @description A grade A reference price and why it is that price.
         */
        RateOut: {
            /** Rate Paise Per Kg */
            rate_paise_per_kg: number;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /**
             * Source
             * @enum {string}
             */
            source: "seed" | "admin" | "market";
            /** Previous Rate Paise Per Kg */
            previous_rate_paise_per_kg: number | null;
            /** Trade Count */
            trade_count: number | null;
            /** Window Days */
            window_days: number | null;
            /** Market Median Paise Per Kg */
            market_median_paise_per_kg: number | null;
            /** Capped */
            capped: boolean;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Phone */
            phone: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "seller" | "buyer";
            /** Business Name */
            business_name?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** Pan */
            pan?: string | null;
        };
        /** ResolveIn */
        ResolveIn: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "settle" | "cancel";
            /** Note */
            note: string;
            /** Weight Grams */
            weight_grams?: number | null;
        };
        /** RfqIn */
        RfqIn: {
            /** Material Code */
            material_code: string;
            /** Quantity Grams */
            quantity_grams: number;
            /** Target Rate Paise Per Kg */
            target_rate_paise_per_kg?: number | null;
            /**
             * Needed By
             * Format: date-time
             */
            needed_by: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** RfqOut */
        RfqOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            buyer: components["schemas"]["PartyOut"];
            /** Material Code */
            material_code: string;
            /** Material Name */
            material_name: string;
            /** Quantity Grams */
            quantity_grams: number;
            /** Target Rate Paise Per Kg */
            target_rate_paise_per_kg: number | null;
            /**
             * Needed By
             * Format: date-time
             */
            needed_by: string;
            /** Note */
            note: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RouteOut */
        RouteOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            depot: components["schemas"]["LocationOut"];
            /** Stops */
            stops: components["schemas"]["RouteStopOut"][];
            /** Unplaced */
            unplaced: components["schemas"]["RouteStopOut"][];
            /** Return Metres */
            return_metres: number;
            /** Total Metres */
            total_metres: number;
        };
        /** RouteStopOut */
        RouteStopOut: {
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            seller: components["schemas"]["PartyOut"];
            /** Material Name */
            material_name: string | null;
            /**
             * Pickup At
             * Format: date-time
             */
            pickup_at: string;
            location: components["schemas"]["LocationOut"] | null;
            /** Leg Metres */
            leg_metres: number | null;
        };
        /** TaxLineOut */
        TaxLineOut: {
            /** Label */
            label: string;
            /** Percent */
            percent: string;
            /** Amount Paise */
            amount_paise: number;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** TransporterIn */
        TransporterIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Vehicle */
            vehicle: string;
            /** Capacity Grams */
            capacity_grams: number;
        };
        /** TransporterOut */
        TransporterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Vehicle */
            vehicle: string;
            /** Capacity Grams */
            capacity_grams: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Business Name */
            business_name: string | null;
            /** Gstin */
            gstin: string | null;
            /** Pan */
            pan: string | null;
            /** Kyc Status */
            kyc_status: string;
            /** Kyc Note */
            kyc_note: string | null;
            /** Authorisations */
            authorisations: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationOut */
        VerificationOut: {
            /**
             * Certificate Id
             * Format: uuid
             */
            certificate_id: string;
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /** Valid */
            valid: boolean;
            /** Reason */
            reason: string | null;
            /** Head Hash */
            head_hash: string;
            /** Event Count */
            event_count: number;
            /** Pdf Sha256 */
            pdf_sha256: string;
        };
        /** WalletEntryOut */
        WalletEntryOut: {
            /** Kind */
            kind: string;
            /** Lot Id */
            lot_id: string | null;
            /** Amount Paise */
            amount_paise: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WalletOut */
        WalletOut: {
            /** Balance Paise */
            balance_paise: number;
            /** Entries */
            entries: components["schemas"]["WalletEntryOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    catalogue_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueOut"];
                };
            };
        };
    };
    rate_history_materials__code__rates_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lots_lots_get: {
        parameters: {
            query?: {
                scope?: "mine" | "market";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lot_lots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_lot_lots_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lot_lots__lot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lot_photo_lots__lot_id__photo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_lot_lots__lot_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lot_lots__lot_id__list_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bids_lots__lot_id__bids_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_bid_lots__lot_id__bids_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_award_lots__lot_id__decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_escrow_lots__lot_id__escrow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_pickup_lots__lot_id__pickup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_delivery_lots__lot_id__delivery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_record_delivery_lots__lot_id__delivery_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weighbridge_slip_lots__lot_id__weighbridge_slip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_delivery_lots__lot_id__delivery_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_delivery_lots__lot_id__delivery_dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_dispute_lots__lot_id__dispute_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    custody_record_lots__lot_id__custody_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustodyEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_lots__lot_id__invoice_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_capture_payments__intent_id__simulate_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    razorpay_verify_payments_razorpay_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutResultIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    razorpay_webhook_payments_razorpay_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    certificate_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    certificate_pdf_certificates__certificate_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificates__certificate_id__verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wallet_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletOut"];
                };
            };
        };
    };
    list_rfqs_rfqs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfqOut"][];
                };
            };
        };
    };
    post_rfq_rfqs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RfqIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfqOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_rfq_rfqs__rfq_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfqOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    partners_agreements_partners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyOut"][];
                };
            };
        };
    };
    list_agreements_agreements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementOut"][];
                };
            };
        };
    };
    propose_agreements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgreementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_agreements__agreement_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_agreements__agreement_id__decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    impact_impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactOut"];
                };
            };
        };
    };
    users_admin_users_get: {
        parameters: {
            query?: {
                kyc_status?: components["schemas"]["KycStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_kyc_admin_users__user_id__kyc_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KycDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_rate_admin_materials__code__rate_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disputes_admin_disputes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeOut"][];
                };
            };
        };
    };
    transporters_admin_transporters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransporterOut"][];
                };
            };
        };
    };
    add_transporter_admin_transporters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransporterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_admin_routes_get: {
        parameters: {
            query: {
                day: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anchors_admin_anchors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"][];
                };
            };
        };
    };
    seal_admin_anchors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorOut"];
                };
            };
        };
    };
    check_admin_anchors__anchor_id__check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anchor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnchorCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_admin_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    run_now_admin_jobs__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
