"""award payment deadline

Revision ID: 41830143895a
Revises: ef159af3577a
Create Date: 2026-10-02 03:56:39.930806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41830143895a'
down_revision: Union[str, Sequence[str], None] = 'ef159af3577a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lapsed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escrow_due_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_column('escrow_due_at')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_column('lapsed_at')

    # ### end Alembic commands ###
