"""settled weight for resolved disputes

Revision ID: 47182b9b7e1b
Revises: a8cf6d0536bc
Create Date: 2026-10-08 02:55:54.212699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47182b9b7e1b'
down_revision: Union[str, Sequence[str], None] = 'a8cf6d0536bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settled_weight_grams', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_column('settled_weight_grams')

    # ### end Alembic commands ###
