"""profiles, lot location, open auctions, transport, notifications, invoices

Revision ID: 980e0360a0b2
Revises: f4ba578f9f36
Create Date: 2026-10-08 15:18:49.070037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980e0360a0b2'
down_revision: Union[str, Sequence[str], None] = 'f4ba578f9f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_grade_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('place', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('pickup_ready_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('location_adjustment_bp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auction_format', sa.String(length=8), server_default='sealed', nullable=False))
        batch_op.add_column(sa.Column('transporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pickup_weight_grams', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lots_place'), ['place'], unique=False)
        batch_op.create_foreign_key('lots_transporter_id_fkey', 'transporters', ['transporter_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('place', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('kyc_document_key', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('kyc_document_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('kyc_document_sha256', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kyc_document_sha256')
        batch_op.drop_column('kyc_document_name')
        batch_op.drop_column('kyc_document_key')
        batch_op.drop_column('place')
        batch_op.drop_column('email')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_constraint('lots_transporter_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lots_place'))
        batch_op.drop_column('pickup_weight_grams')
        batch_op.drop_column('transporter_id')
        batch_op.drop_column('auction_format')
        batch_op.drop_column('location_adjustment_bp')
        batch_op.drop_column('pickup_ready_on')
        batch_op.drop_column('place')
        batch_op.drop_column('suggested_grade_confidence')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('invoices')
    # ### end Alembic commands ###
