"""started modules

Revision ID: a8cf6d0536bc
Revises: 41830143895a
Create Date: 2026-10-08 00:08:15.548099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cf6d0536bc'
down_revision: Union[str, Sequence[str], None] = '41830143895a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_event_id', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_event_id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_name'), ['name'], unique=False)

    op.create_table('transporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('vehicle', sa.String(length=120), nullable=False),
    sa.Column('capacity_grams', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfqs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_grams', sa.BigInteger(), nullable=False),
    sa.Column('target_rate_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('needed_by', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfqs_buyer_id'), ['buyer_id'], unique=False)

    op.create_table('supply_agreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('monthly_quantity_grams', sa.BigInteger(), nullable=False),
    sa.Column('rate_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_agreements_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_agreements_seller_id'), ['seller_id'], unique=False)

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorisation', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorisations', sa.String(length=100), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('authorisations')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('authorisation')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_column('pickup_longitude')
        batch_op.drop_column('pickup_latitude')

    with op.batch_alter_table('supply_agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_agreements_seller_id'))
        batch_op.drop_index(batch_op.f('ix_supply_agreements_buyer_id'))

    op.drop_table('supply_agreements')
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfqs_buyer_id'))

    op.drop_table('rfqs')
    op.drop_table('transporters')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_name'))

    op.drop_table('job_runs')
    op.drop_table('custody_anchors')
    # ### end Alembic commands ###
