"""initial schema

Revision ID: ef159af3577a
Revises: 
Create Date: 2026-10-01 01:40:55.758223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef159af3577a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('kyc_status', sa.String(length=16), nullable=False),
    sa.Column('kyc_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('photo_key', sa.String(length=300), nullable=False),
    sa.Column('photo_sha256', sa.String(length=64), nullable=False),
    sa.Column('suggested_material_code', sa.String(length=40), nullable=True),
    sa.Column('suggested_grade', sa.String(length=1), nullable=True),
    sa.Column('suggestion_confidence', sa.Float(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=True),
    sa.Column('declared_weight_grams', sa.BigInteger(), nullable=True),
    sa.Column('reference_rate_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('estimate_rate_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('estimate_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('estimate_low_paise', sa.BigInteger(), nullable=True),
    sa.Column('estimate_high_paise', sa.BigInteger(), nullable=True),
    sa.Column('reserve_rate_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('auction_closes_at', sa.DateTime(), nullable=True),
    sa.Column('awarded_buyer_id', sa.Uuid(), nullable=True),
    sa.Column('awarded_rate_paise_per_kg', sa.BigInteger(), nullable=True),
    sa.Column('pickup_at', sa.DateTime(), nullable=True),
    sa.Column('measured_weight_grams', sa.BigInteger(), nullable=True),
    sa.Column('weighbridge_slip_key', sa.String(length=300), nullable=True),
    sa.Column('weighbridge_slip_sha256', sa.String(length=64), nullable=True),
    sa.Column('settled_amount_paise', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_status'), ['status'], unique=False)

    op.create_table('reference_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('rate_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('set_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('rate_paise_per_kg', sa.BigInteger(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'buyer_id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_lot_id'), ['lot_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('pdf_key', sa.String(length=300), nullable=False),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_table('custody_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'seq')
    )
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custody_events_lot_id'), ['lot_id'], unique=False)

    op.create_table('ledger_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('payment_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gateway', sa.String(length=16), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=64), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_order_id'),
    sa.UniqueConstraint('gateway_payment_id')
    )
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_intents_lot_id'), ['lot_id'], unique=False)

    op.create_table('ledger_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_postings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_postings_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_postings_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_postings_account_id'))

    op.drop_table('ledger_postings')
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intents_lot_id'))

    op.drop_table('payment_intents')
    op.drop_table('ledger_transactions')
    op.drop_table('ledger_accounts')
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custody_events_lot_id'))

    op.drop_table('custody_events')
    op.drop_table('certificates')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_lot_id'))

    op.drop_table('bids')
    op.drop_table('reference_rates')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_status'))

    op.drop_table('lots')
    op.drop_table('users')
    op.drop_table('materials')
    # ### end Alembic commands ###
