"""rate basis for dynamic pricing

Revision ID: f4ba578f9f36
Revises: 47182b9b7e1b
Create Date: 2026-10-08 14:10:07.130894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ba578f9f36'
down_revision: Union[str, Sequence[str], None] = '47182b9b7e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_rate_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('lots_reference_rate_id_fkey', 'reference_rates', ['reference_rate_id'], ['id'])

    with op.batch_alter_table('reference_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=12), server_default='admin', nullable=False))
        batch_op.add_column(sa.Column('previous_rate_paise_per_kg', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('trade_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('window_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('market_median_paise_per_kg', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('capped', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###
    # Rates with no admin behind them came from the starting catalogue (seed, or seed-demo's
    # back-dated copies); everything else was set on the admin prices screen.
    op.execute("UPDATE reference_rates SET source = 'seed' WHERE set_by_id IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_rates', schema=None) as batch_op:
        batch_op.drop_column('capped')
        batch_op.drop_column('market_median_paise_per_kg')
        batch_op.drop_column('window_days')
        batch_op.drop_column('trade_count')
        batch_op.drop_column('previous_rate_paise_per_kg')
        batch_op.drop_column('source')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_constraint('lots_reference_rate_id_fkey', type_='foreignkey')
        batch_op.drop_column('reference_rate_id')

    # ### end Alembic commands ###
